import Header from '@/components/UI/header/Header'
import type { Metadata } from 'next'
import ReactQueryProvider from '../lib/providers/ReactQueryProvider'
import StoreProvider from '../lib/providers/StoreProvider'
import './globals.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body>
				<StoreProvider>
					<ReactQueryProvider>
						<Header />
						{children}
					</ReactQueryProvider>
				</StoreProvider>
			</body>
		</html>
	)
}
